version: '3'

vars:
  BASE_STYLE_PATH: .

tasks:
  merge-styles:
    desc: merge-styles
    cmds:
      - |
        jq -r '.layers[]' {{.BASE_STYLE_PATH}}/def/test_style_def.json | while read layer; do
          if [ -f "{{.BASE_STYLE_PATH}}/${layer}_style.json" ]; then
            echo "{{.BASE_STYLE_PATH}}/${layer}_style.json"
          fi
        done > style_files.txt
      - |
        jq '
          .layers |= map(
            . as $layer |
            if (. | type == "string") and ($layer + "_style.json" | IN(inputs)) then
              input | .layers[]
            else
              $layer
            end
          )
        ' {{.BASE_STYLE_PATH}}/def/test_style_def.json $(cat style_files.txt) > merged_style.json
      - rm style_files.txt
    silent: true

  default:
    cmds:
      - task: merge-styles
